<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCukxmk7\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCukxmk7/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerCukxmk7.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerCukxmk7\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerCukxmk7\appProdProjectContainer([
    'container.build_hash' => 'Cukxmk7',
    'container.build_id' => '5898b8ea',
    'container.build_time' => 1645366493,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCukxmk7');
